#!/bin/sh -e

mkdir -p ${SNAP_COMMON}/config
mkdir -p ${SNAP_COMMON}/maps

# Copy default map and create symlink during installation
cp ${SNAP}/usr/share/ros2-nav2/maps/default_map.yaml ${SNAP_COMMON}/maps/default_map.yaml
cp ${SNAP}/usr/share/ros2-nav2/maps/default_map.png ${SNAP_COMMON}/maps/default_map.png
ln -sf ${SNAP_COMMON}/maps/default_map.yaml ${SNAP_COMMON}/maps/current_map.yaml


. ${SNAP}/usr/bin/reset_config.sh

# set default configuration values
snapctl set simulation="False"
snapctl set slam-config!
snapctl set navigation-config!
snapctl set localization-config!
snapctl set map="${SNAP_COMMON}/maps/current_map.yaml"
snapctl set map-yaml-path!
snapctl set map-saver-config!

if ! snapctl is-connected ros-humble; then
  logger -t ${SNAP_NAME} "Plug 'ros-humble' isn't connected, \
    please run: snap connect ${SNAP_NAME}:ros-humble <providing-snap>"
fi
